name: WtfAuth
version: '${project.version}'
main: pl.loveese.WtfAuth
api-version: 1.18
author: loveese
softdepend: [PlaceholderAPI, LuckPerms, ProtocolLib]

commands:
  register:
  login:
  changepassword:
  info:
